spring.application.name=home-inventory

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/home_inventory}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:home_inventory}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:home_inventory}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
