apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: home-inventory
type: Opaque
stringData:
  POSTGRES_DB: home_inventory
  POSTGRES_USER: home_inventory
  POSTGRES_PASSWORD: home_inventory
